### ISSUE TITLE
`std::old_io::IoResult`. Could not find `old_io` in `std`

### ISSUE THREAD

**Issue by dicos** [mattnenterprise/rust-ftp#2]
$ cargo run
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading ftp v0.0.4
 Downloading regex-syntax v0.1.2
 Downloading regex v0.1.33
   Compiling regex-syntax v0.1.2
   Compiling regex v0.1.33
   Compiling ftp v0.0.4
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8:19: 8:27 error: unresolved import `std::old_io::IoResult`. Could not find `old_io` in `std`
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8 use std::old_io::{IoResult, TcpStream, BufferedReader, BufferedWriter, MemReader, EndOfFile};
                                                                                                      ^~~~~~~~
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8:29: 8:38 error: unresolved import `std::old_io::TcpStream`. Could not find `old_io` in `std`
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8 use std::old_io::{IoResult, TcpStream, BufferedReader, BufferedWriter, MemReader, EndOfFile};
                                                                                                                ^~~~~~~~~
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8:40: 8:54 error: unresolved import `std::old_io::BufferedReader`. Could not find `old_io` in `std`
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8 use std::old_io::{IoResult, TcpStream, BufferedReader, BufferedWriter, MemReader, EndOfFile};
                                                                                                                           ^~~~~~~~~~~~~~
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8:56: 8:70 error: unresolved import `std::old_io::BufferedWriter`. Could not find `old_io` in `std`
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8 use std::old_io::{IoResult, TcpStream, BufferedReader, BufferedWriter, MemReader, EndOfFile};
                                                                                                                                           ^~~~~~~~~~~~~~
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8:72: 8:81 error: unresolved import `std::old_io::MemReader`. Could not find `old_io` in `std`
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8 use std::old_io::{IoResult, TcpStream, BufferedReader, BufferedWriter, MemReader, EndOfFile};
                                                                                                                                                           ^~~~~~~~~
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8:83: 8:92 error: unresolved import `std::old_io::EndOfFile`. Could not find `old_io` in `std`
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:8 use std::old_io::{IoResult, TcpStream, BufferedReader, BufferedWriter, MemReader, EndOfFile};
                                                                                                                                                                      ^~~~~~~~~
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:11:5: 11:28 error: unresolved import `std::old_io::util::copy`. Could not find `old_io` in `std`
/home/dmitry/.cargo/registry/src/github.com-1285ae84e5963aae/ftp-0.0.4/src/ftp.rs:11 use std::old_io::util::copy;
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 7 previous errors
Could not compile `ftp`.

To learn more, run the command again with --verbose.

$ rustc --version
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)

**Comment by bombless** [comment]
You can wait for author to update the crate in crates.io or you can use my PR.

**Comment by mattnenterprise** [comment]
This has been resolved
