### ISSUE TITLE
Host documentation on Github pages

### ISSUE THREAD

**Issue by matt2xu** [mattnenterprise/rust-ftp#26]
This is something that I have seen some other crates do, and it would be quite helpful for users of this crate. I have no idea how Github pages are set up though. @mattnenterprise what is your opinion on this?

**Comment by dbrgn** [comment]
https://github.com/huonw/travis-cargo can help with this.

**Comment by mattnenterprise** [comment]
I think this would be a great thing to do.

**Comment by mattnenterprise** [comment]
I have used https://github.com/huonw/travis-cargo to create documentation. A link to it is in the README.  So I am going to consider this finished unless someone has something else to add.

**Comment by dbrgn** [comment]
Looks good :)
