### ISSUE TITLE
Set Read/Write Timeout

### ISSUE THREAD

**Issue by msiemens** [mattnenterprise/rust-ftp#52]
As far as I can tell, currently there's no way to set the used TCPStream's read/write timeout. Doing so would be very handy if the server is unresponsive. If this isn't too hard to do, I'd love to contribute a Pull Request. What do you think?

**Comment by matt2xu** [comment]
Good idea. Alternatively, what about adding a inner() method that returns a &TcpStream?

**Comment by mattnenterprise** [comment]
I would like to see this feature added.

**Comment by mattnenterprise** [comment]
@msiemens Thanks for letting up know about this issue.
