### ISSUE TITLE
Make the code more ergonomic

### ISSUE THREAD

**Issue by matt2xu** [mattnenterprise/rust-ftp#56]
Taking a new look at this crate after several months, it's looking great!
I have a few ideas to make the code more ergonomic, for instance replacing explicit drops by out-of-scope automatic drops, using AsRef<&str> or Into<Cow<'a, str>>, rewriting simple_retr_ to avoid a clone, this kind of things. Would you be interested in a PR with these changes?

**Comment by mattnenterprise** [comment]
Go for it!
