### ISSUE TITLE
Consider using Clippy on the crate

### ISSUE THREAD

**Issue by Luxed** [mattnenterprise/rust-ftp#71]
Everything is in the title.
[Clippy](https://github.com/rust-lang-nursery/rust-clippy)

Inconvenience:
- Clippy requires rust nightly to work.

As always, I will test this in a separate branch and commit a PR if I find that it works well.

**Comment by mattnenterprise** [comment]
Clippy was added to run in CI in https://github.com/mattnenterprise/rust-ftp/pull/101.
