### ISSUE TITLE
CDUP returns 200, not 250

### ISSUE THREAD

**Issue by antoyo** [mattnenterprise/rust-ftp#73]
Hi.
According to the RFC, the CDUP command should return 200, not 250 (like the CWD command), so [this line](https://github.com/mattnenterprise/rust-ftp/blob/3de12e12a71fff6971815016e3386418c207fa79/src/ftp.rs#L207) is incorrect.
Thanks to fix this issue.

**Comment by Luxed** [comment]
I will look into this.

**Comment by Luxed** [comment]
Since my fork is a mess right now, I do not want to make another PR.

You can pull the repo here (or the PR with openssl 0.9 used) and change the `cdup()` function to this:
```rust
pub fn cdup(&mut self) -> Result<()> {
    try!(self.write_str("CDUP\r\n"));
    self.read_response_in(&[status::REQUESTED_FILE_ACTION_OK, status::COMMAND_OK]).map(|_| ())
}
```
