### ISSUE TITLE
Status of rust-ftp

### ISSUE THREAD

**Issue by emoon** [mattnenterprise/rust-ftp#90]
Hi,

I wonder what the current status is given that there are a bunch of PRs being open that fixes some fairly important issues (such as version of openssl) is this crate still being supported or not?

**Comment by emoon** [comment]
Friendly ping @mattnenterprise

**Comment by ThouCheese** [comment]
It might be time to fork this project sadly :disappointed:

**Comment by emoon** [comment]
Problem is that there are several forks already (just looking at the ones on GH) but no "official" fork of it

**Comment by emoon** [comment]
As there has been some updates after I posted this I think I can close it :)
